version: '3.8'

services:

  docker-ansible-centos7:
    image: jdeathe/centos-ssh
    restart: always
    container_name: docker-ansible-centos7
    hostname: docker-ansible-centos7

    volumes:
      - type: bind
        source: .
        target: /root/project

    ports:
        - "3333:22"

    environment:
      SSH_USER: "root"
      SSH_USER_PASSWORD: "root"
      SSH_PASSWORD_AUTHENTICATION: "true"
      SSH_USER_HOME: "/root"
