- name: 檢查掛載點是否已有其他加密碟掛載
  block:
    - name: 檢查 掛載點 掛載情況
      shell: "{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }} -l | grep {{ veracrypt_mount_point }} |awk '{print $4; exit;}'"
      register: check_mount_point_by_veracrypt
      ignore_errors: True

    - name: 列印出檢查結果
      debug:
        msg: "檢查結果：{{ check_mount_point_by_veracrypt }}"

    - name: 檢查到 目標掛載點 已被 veracrypt 使用其他硬碟掛載，解除掛載
      become: True
      command:
        argv:
          - "{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }}"
          - "-d"
          - "{{ veracrypt_mount_point }}"
      when: veracrypt_mount_point in check_mount_point_by_veracrypt.stdout
