- name: 安裝 epel 軟題來源
  become: True
  yum:
    name: epel-release
    state: latest

- name: 安裝依賴軟體
  become: True
  yum:
    name:
      - fuse-devel
      - binutils-devel
      - yasm
      - gcc-c++
      - make
    state: latest

- name: 建立臨時部署用的目錄
  file:
    path: "{{ deploy_path }}"
    state: directory
    mode: '0755'

- name: 下載並解壓縮 veracrypt 所需的函式庫（wxWidgets）
  unarchive:
    src: "{{ wxWidgets_download_url }}"
    dest: "{{ deploy_path }}"
    remote_src: yes

- name: 下載 veracrypt 官方源碼
  unarchive:
    src: "{{ veracrypt_download_url }}"
    dest: "{{ deploy_path }}"
    remote_src: yes
