- name: 檢查 veracrypt 執行檔與確認硬碟是否已被 veracrypt 掛載
  include: umount_veracrypt.yml

- name: 產生 veracrypt 掛載用的隨機密碼
  set_fact:
    veracrypt_password: "{{ lookup('community.general.random_string', length=32) }}"

- name: 產生 veracrypt 掛載用的隨機 PIM 碼
  set_fact:
    veracrypt_pim: "{{ 10000 |random(seed=inventory_hostname) }}"

- name: 開始加密：加密碟模式
  become: True
  block:
    - name: 加密碟模式：印出相關資訊，以防使用者遺失加密資訊
      debug:
        msg:
          - "主機名稱：{{ inventory_hostname }}"
          - "加密模式：{{ veracrypt_mode }}"
          - "verarypt 執行檔路徑：{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }}"
          - "目標硬碟：{{ veracrypt_source_media }}"
          - "掛載點：{{ veracrypt_mount_point }}"
          - "指定使用的檔案系統：{{ veracrypt_filesystem }}"
          - "掛載密碼：{{ veracrypt_password }}"
          - "掛載 PIM 碼：{{ veracrypt_pim }}"

    - name: 加密碟模式：開始加密
      command:
        argv:
          - "{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }}"
          - "--create"
          - "{{ veracrypt_source_media }}"
          - "--quick"
          - "--encryption=AES"
          - "--filesystem={{ veracrypt_filesystem }}"
          - "--hash=SHA512"
          - "--volume-type=normal"
          - "--password={{ veracrypt_password }}"
          - "--pim={{ veracrypt_pim }}"
          - "--random-source=/dev/urandom"
          - "--keyfiles="
  when: veracrypt_mode == "disk"

- name: 開始加密：加密卷模式
  become: True
  block:
    - name: 加密卷模式：印出相關資訊，以防使用者遺失加密資訊
      debug:
        msg:
          - "主機名稱：{{ inventory_hostname }}"
          - "加密模式：{{ veracrypt_mode }}"
          - "verarypt 執行檔路徑：{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }}"
          - "目標卷：{{ veracrypt_source_media }}"
          - "目標卷的大小：{{ veracrypt_volume_size }}"
          - "掛載點：{{ veracrypt_mount_point }}"
          - "指定使用的檔案系統：{{ veracrypt_filesystem }}"
          - "掛載密碼：{{ veracrypt_password }}"
          - "掛載 PIM 碼：{{ veracrypt_pim }}"

    - name: 加密卷模式：開始加密
      command:
        argv:
          - "{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }}"
          - "--create"
          - "{{ veracrypt_source_media }}"
          - "--quick"
          - "--encryption=AES"
          - "--filesystem={{ veracrypt_filesystem }}"
          - "--hash=SHA512"
          - "--volume-type=normal"
          - "--password={{ veracrypt_password }}"
          - "--pim={{ veracrypt_pim }}"
          - "--random-source=/dev/urandom"
          - "--keyfiles="
          - "--size={{ veracrypt_volume_size }}"

  when: veracrypt_mode == "volume"

- name: 加密完成：使用 mount -a 檢查掛載點
  include: mount_all_check.yml

- name: 加密完成：掛載硬碟/卷（xfs 以外）
  include: mount_veracrypt.yml
  when: veracrypt_filesystem != "xfs"

- name: 加密完成：掛載硬碟/卷（xfs）
  become: True
  block:
    - name: 檢查掛載點是否已有其他加密碟掛載
      include: check_mount_point.yml

    - name: xfs 初始化：暫時以 none 掛載硬碟
      command:
        argv:
          - "{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }}"
          - "--filesystem=none"
          - "{{ veracrypt_source_media }}"
          - "{{ veracrypt_mount_point }}"
          - "--password={{ veracrypt_password }}"
          - "--pim={{ veracrypt_pim }}"
          - "--keyfiles="
          - "--non-interactive"

    - name: 獲取掛載後的硬碟路徑
      shell: "{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }} -l | grep {{ veracrypt_source_media }} |awk '{print $3; exit;}'"
      register: tempVeracryptMountPath

    - name: xfs 初始化：以 xfs 格式來格式化硬碟
      community.general.filesystem:
        fstype: xfs
        dev: "{{ tempVeracryptMountPath.stdout }}"

    - name: xfs 初始化：卸載硬碟
      include: umount_veracrypt.yml

    - name: xfs 初始化：重新掛載硬碟
      include: mount_veracrypt.yml
  when: veracrypt_filesystem == "xfs"

- name: 將加密碟資訊寫回本地端
  delegate_to: localhost
  run_once: True
  template:
    src: "{{ veracrypt_result }}.j2"
    dest: "{{ playbook_dir }}/../{{ veracrypt_result }}"
    mode: "0400"

- name: 輸出轉換結果
  delegate_to: localhost
  run_once: True
  debug:
    msg: '轉換成功，檔案保存於 {{ playbook_dir }}/../{{ veracrypt_result }}'
