- name: 檢查 /etc/fstab 是否有包含欲加密磁碟之資訊
  block:
    - name: 獲取加密磁碟的 UUID
      failed_when: False
      changed_when: False
      register: veracrypt_source_media_uuid
      command: "blkid -sUUID -ovalue {{ veracrypt_source_media }}"

    - name: 檢查 /etc/fstab 是否有包含「加密磁碟路徑」
      when: veracrypt_source_media != ""
      block:
        - name: 檢查 /etc/fstab 內容中是否存在 veracrypt_source_media 的自動掛載配置（區塊裝置路徑）
          check_mode: yes
          register: check_fstab_disk_path
          lineinfile:
            path: /etc/fstab
            regexp: "{{ veracrypt_source_media }}"
            state: absent

        - name: 移除 veracrypt_source_media 的自動掛載配置（區塊裝置路徑）
          when: check_fstab_disk_path.found
          lineinfile:
            dest: /etc/fstab
            regexp: "{{ veracrypt_source_media }}"
            state: absent

    - name: 檢查 /etc/fstab 是否有包含加密磁碟 UUID
      when: veracrypt_source_media_uuid.stdout != ""
      block:
        - name: 檢查 /etc/fstab 內容中是否存在 veracrypt_source_media 的自動掛載配置（UUID）
          register: check_fstab_disk_uuid
          check_mode: yes
          lineinfile:
            path: /etc/fstab
            regexp: "{{ veracrypt_source_media_uuid.stdout }}"
            state: absent

        - name: 移除 veracrypt_source_media 的自動掛載配置（UUID 唯一識別編號）
          lineinfile:
            dest: /etc/fstab
            regexp: "{{ veracrypt_source_media_uuid.stdout }}"
            state: absent

- name: mount -a 測試
  include: check-automount.yml
