- name: 檢查 /etc/fstab 是否有包含欲加密磁碟之資訊
  block:
    - name: 獲取加密磁碟的 UUID
      become: True
      command: "blkid -sUUID -ovalue {{ veracrypt_source_media }}"
      register: veracrypt_source_media_uuid
      ignore_errors: True

    - name: 列印加密硬碟的 UUID
      debug:
        msg: "{{ veracrypt_source_media }} 的 UUID 資訊：{{ veracrypt_source_media_uuid.stdout }}"

    - name: 檢查 /etc/fstab 是否有包含「加密磁碟路徑」
      block:
        - name: 檢查 /etc/fstab 內容（磁碟路徑）
          lineinfile:
            path: /etc/fstab
            regexp: "{{ veracrypt_source_media }}"
            state: absent
          check_mode: yes
          register: check_fstab_disk_path

        - name: 檢查結果：「加密磁碟路徑」並未存在於 /etc/fstab
          debug:
            msg:
              - "測試結果：{{ veracrypt_source_media }} 並未存在於 /etc/fstab"
              - "測試紀錄：{{ check_fstab_disk_path }}"
          when: not check_fstab_disk_path.found

        - name: 檢查結果：「加密磁碟路徑」存在於 /etc/fstab
          block:
            - name: umount 該磁碟
              become: True
              mount:
                path: "{{ veracrypt_source_media }}"
                state: unmounted

            - name: 移除該行位於 /etc/fstab 的掛載設定
              become: True
              lineinfile:
                dest: /etc/fstab
                regexp: "{{ veracrypt_source_media }}"
                state: absent

            - name: 獲取 /etc/fstab 內容
              command: cat /etc/fstab
              register: fstab_content

            - name: 列印出修改完成後的 fstab
              vars:
                msg: "{{ fstab_content.stdout }}"
              debug:
                msg: "{{ msg.split('\n') }}"
          when: check_fstab_disk_path.found
      when: veracrypt_source_media != ""

    - name: 檢查 /etc/fstab 是否有包含加密磁碟 UUID
      block:
        - name: 檢查 /etc/fstab 內容（UUID）
          lineinfile:
            path: /etc/fstab
            regexp: "{{ veracrypt_source_media_uuid.stdout }}"
            state: absent
          check_mode: yes
          register: check_fstab_disk_uuid

        - name: 檢查結果：「加密磁碟 UUID」並未存在於 /etc/fstab
          debug:
            msg:
              - "測試結果：{{ veracrypt_source_media_uuid.stdout }} 並未存在於 /etc/fstab"
              - "測試紀錄：{{ check_fstab_disk_uuid }}"
          when: not check_fstab_disk_uuid.found

        - name: 檢查結果：「加密磁碟 UUID」存在於 /etc/fstab
          block:
            - name: umount 該磁碟
              become: True
              mount:
                path: "UUID={{ veracrypt_source_media_uuid }}"
                state: unmounted

            - name: 移除該行位於 /etc/fstab 的掛載設定
              become: True
              lineinfile:
                dest: /etc/fstab
                regexp: "{{ veracrypt_source_media_uuid.stdout }}"
                state: absent

            - name: 獲取 /etc/fstab 內容
              command: cat /etc/fstab
              register: fstab_content

            - name: 列印出修改完成後的 fstab
              vars:
                msg: "{{ fstab_content.stdout }}"
              debug:
                msg: "{{ msg.split('\n') }}"
          when: check_fstab_disk_uuid.found
      when: veracrypt_source_media_uuid.stdout != ""

- name: mount -a 測試
  include: mount_all_check.yml

- name: 檢查 mount 列表裡是否還存在該硬碟
  block:
    - name: 獲取全系統 mount 清單
      command: "mount | egrep '{{ veracrypt_source_media }}|{{ veracrypt_source_media_uuid.stdout }}'"
      args:
        warn: no
      register: check_mount_after_rm_fstab
      failed_when: check_mount_after_rm_fstab.rc == 0

    - name: 檢查 mount 清單
      fail:
        msg: "硬碟：{{ veracrypt_source_media }}, UUID：{{ veracrypt_source_media_uuid }} 仍被掛載，請登入系統查看問題！"
      when: check_mount_after_rm_fstab.rc == 0
