- name: 編譯 wxWidgets 函式庫
  make:
    chdir: "{{ deploy_path }}/{{ veracrypt_compile_dir_name }}"
    target: wxbuild
    params:
      NOGUI: 1
      WXSTATIC: 1
      WX_ROOT: "{{ deploy_path }}/{{ wxWidgets_complile_dir_name }}"

- name: 編譯 veracrypt 主程式
  make:
    chdir: "{{ deploy_path }}/{{ veracrypt_compile_dir_name }}"
    params:
      NOGUI: 1
      WXSTATIC: 1

- name: 產生隨機的 veracrypt binary 名稱
  set_fact:
    veracrypt_executable: "{{ lookup('community.general.random_string', length=8, special=false) }}"

- name: 移動 veracrypt binary 到指定的安裝目錄
  become: True
  copy:
    remote_src: yes
    src: "{{ deploy_path }}/{{ veracrypt_compile_dir_name }}/Main/veracrypt"
    dest: "{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }}"
    mode: "0755"

- name: Veracrypt 主程式安裝完成：列印 veracrypt binary 安裝路徑
  debug:
    msg: "veracrypt 執行檔路徑：{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }}"

- name: 移除臨時的 veracrypt 編譯資料夾
  file:
    path: "{{ deploy_path }}"
    state: absent
