- name: 使用 mount -a 檢查掛載點
  become: True
  block:
    - name: 執行 mount -a
      command: mount -a
      args:
        warn: no
      register: mountTestOutput
      ignore_errors: True

    - name: 檢查 mount -a 測試結果
      fail:
        msg: "機器 {{ inventory_hostname }} mount -a 檢查失敗！請登入機器檢查掛載，尤其是 /etc/fstab"
      when: mountTestOutput.rc != 0
