- name: 驗證 veracrypt 執行檔是否正常
  block:
    - name: 檢查 veracrypt 執行檔
      shell: "{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }} --version | grep -i VeraCrypt"
      register: check_veracrypt_bin
      ignore_errors: True

    - name: 確認 veracrypt 執行檔檢查結果
      fail:
        msg:
          - "Veracrypt 執行檔：{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }} 有錯誤！"
          - "return code: {{ check_veracrypt_bin.rc }}"
          - "錯誤內容：{{ check_veracrypt_bin.stderr }}"
      when: check_veracrypt_bin.rc != 0

- name: 檢查欲掛載加密碟/卷，是否已被掛載
  include: umount_veracrypt.yml

- name: 檢查掛載點是否已有其他加密碟掛載
  include: check_mount_point.yml

- name: 開始掛載
  become: True
  command:
    argv:
      - "{{ veracrypt_bin_install_path }}/{{ veracrypt_executable }}"
      - "{{ veracrypt_source_media }}"
      - "{{ veracrypt_mount_point }}"
      - "--password={{ veracrypt_password }}"
      - "--pim={{ veracrypt_pim }}"
      - "--keyfiles="
      - "--non-interactive"
