all:
  vars:
    wg_dns_address: 192.168.33.2
    wg_server_public_key: "key"
    wg_endpoint: "1.2.3.4:51820"
    wg_allowed_ips: "192.168.33.0/24"

  hosts:
    master:
      ansible_host: 192.168.56.11
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: '{{ inventory_dir }}/../.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key'

      wg_client_address: 192.168.33.4
      wg_client_private_key: "key"
      wg_client_port: 51820

      veracrypt_mode: volume
      veracrypt_source_media: ""
      veracrypt_filesyste: xfs
      veracrypt_volume_size: "5G"

    node1:
      ansible_host: 192.168.56.12
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: '{{ inventory_dir }}/../.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key'

      wg_client_address: 192.168.33.5
      wg_client_private_key: "key"
      wg_client_port: 51820

      veracrypt_mode: volume
      veracrypt_source_media: ""
      veracrypt_filesyste: xfs
      veracrypt_volume_size: "5G"

    node2:
      ansible_host: 192.168.56.13
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: '{{ inventory_dir }}/../.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key'

      wg_client_address: 192.168.33.6
      wg_client_private_key: "key"
      wg_client_port: 51820

      veracrypt_mode: volume
      veracrypt_source_media: ""
      veracrypt_filesyste: xfs
      veracrypt_volume_size: "5G"

  children:
    wireguard_client:
      hosts:
        master:
        node1:
        node2:
