- name: set hostname
  ansible.builtin.hostname:
    use: systemd
    name: "{{ inventory_hostname }}"

- name: set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: stop firewalld
  systemd:
    state: stopped
    name: firewalld
    enabled: no

- name: disable selinux
  shell: "setenforce 0"

- name: update selinux config
  ansible.builtin.replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=[a-z]*'
    replace: 'SELINUX=disabled'

- name: remove unnecessary packages
  yum:
    name:
      - postfix
      - mysql-libs
      - mariadb*
      - gssproxy
    state: absent

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install useful packages
  yum:
    name:
      - vim
      - htop
      - net-tools
      - iftop
      - iotop
      - unhide
      - zip
      - unzip
      - lsof
      - wget
      - telnet
      - p7zip
      - rsync
    state: present

- name: Stop and Disable the rpcbind services
  systemd:
    name: rpcbind
    enabled: no
    state: stopped
  register: rpcbind_service_result
  failed_when: "rpcbind_service_result is failed and 'Could not find the requested service' not in rpcbind_service_result.msg"

- name: Stop and Disable the rpcbind.socket services
  systemd:
    name: rpcbind.socket
    enabled: no
    state: stopped
  register: rpcbind_socket_service_result
  failed_when: "rpcbind_socket_service_result is failed and 'Could not find the requested service' not in rpcbind_socket_service_result.msg"

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Add ELRepo
  yum:
    name: "{{ elrepo_download_url  }}"
    state: latest

- name: Install latest mainline kernel
  yum:
    name: kernel-ml
    state: latest
    enablerepo: elrepo-kernel

- name: Remove elrepo-release package
  yum:
    name: elrepo-release
    state: removed

- name: Remake grub config to pick up new kernel
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Set grub menu to entry 0
  command: grub2-set-default 0

- name: Remove default system users
  user:
    name: "{{ item }}"
    state: absent
  loop: "{{ deleted_user_names }}"

- name: reboot
  reboot:
