- name: set hostname
  become: True
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: set timezone
  become: True
  community.general.timezone:
    name: Asia/Taipei

- name: stop firewalld
  become: True
  ansible.builtin.systemd:
    state: stopped
    name: firewalld
    enabled: no

- name: disable selinux
  become: True
  shell: "setenforce 0"

- name: update selinux config
  become: True
  ansible.builtin.replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=[a-z]*'
    replace: 'SELINUX=disabled'

- name: upgrade all packages
  become: True
  yum:
    name: '*'
    state: latest

- name: reboot
  become: True
  reboot:
