- name: Remove installed old version of docker
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: removed

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: add docker repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker engine
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest

- name: Create Docker config store directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Config docker install path
  when: is_config_docker_install_path == true
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
    owner: root
    group: root

- name: Start and enable dockerd with systemd
  when: enable_docker == true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
