veracrypt_mode: "volume"
veracrypt_filesystem: "xfs"
veracrypt_source_media: ""
veracrypt_mountpoint: "/opt"
veracrypt_version: 1.24-Update7
veracrypt_volume_size: "1G"
veracrypt_volume_directory: "/usr/share/man"
veracrypt_bin_install_path: "/usr/local/share/man/man4x"
