- name: install yum ELRepo
  yum:
    name:
      - epel-release
      - elrepo-release

- name: install yum elrepo plugin
  yum:
    name: yum-plugin-elrepo

- name: install wireguard kernel module
  yum:
    name:
      - kmod-wireguard
      - wireguard-tools

- name: Reboot to apply module
  reboot:

- name: Add wireguard module
  community.general.modprobe:
    name: wireguard
    state: present

- name: make wireguard-client config directory
  file:
    path: "{{ wg_installed_path }}"
    state: directory

- name: copy wireguard config
  template:
    src: wg0.conf.j2
    dest: "{{ wg_installed_path }}/wg0.conf"
    mode: 0600

- name: start wireguard
  shell: "wg-quick up {{ wg_installed_path }}/wg0.conf"
