- name: get docker prebuilt binary
  get_url:
     url: "https://download.docker.com/linux/static/stable/{{ os_arch }}/docker-{{ docker_version }}.tgz"
     dest: /tmp

- name: unarchive prebuild binary file
  unarchive:
    remote_src: yes
    src: "/tmp/docker-{{ docker_version }}.tgz"
    dest: "/tmp"
    owner: root
    group: root
    mode: '0755'


- name: create installed path and directories
  file:
    path: "{{ docker_install_path }}/bin"
    state: directory

- name: create logs directory
  file:
    path: "{{ docker_install_path }}/logs"
    state: directory

- name: move binaries to installed path
  shell: mv /tmp/docker/* {{ docker_install_path }}/bin

- name: create start scripts
  template:
    src: start.sh.j2
    dest: "{{ docker_install_path }}/bin/start"
    mode: 0755

- name: create stop script
  template:
    src: stop.sh.j2
    dest: "{{ docker_install_path }}/bin/stop"
    mode: 0755

- name: start docker daemon
  command: "{{ docker_install_path }}/bin/start"

- name: install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ os }}-{{ os_arch }}"
    dest: "{{ docker_install_path }}/bin/docker-compose"
    mode: 0755

- name: update $PATH variable
  shell: "echo 'PATH=${PATH}:{{ docker_install_path }}/bin' > /etc/profile.d/docker.sh"

- name: test docker
  command: "{{ docker_install_path }}/bin/docker --version"
  register: output_docker

- name: test docker compose
  command: "{{ docker_install_path }}/bin/docker-compose --version"
  register: output_docker_compose

- debug: var=output_docker.stdout_lines
- debug: var=output_docker_compose.stdout_lines
